#!/usr/bin/env node
// CLA-29 visual-verification artifact generator.
// Builds ONE self-contained HTML file that puts labelled image panels side by
// side (Before / Proposed / Final) so the owner can verify a shipped visual
// result against the agreed target. Images are base64-embedded so the HTML is
// portable (no external paths, can be opened or published anywhere).
//
// Usage:
//   node scripts/visual-compare.mjs \
//     --title "CLA-19 density legibility" \
//     --out docs/visual-targets/cla-19/compare.html \
//     --panel "Before (original)=/abs/before.png" \
//     --panel "Proposed (mockup)=/abs/proposed.png" \
//     --panel "Final (shipped)=/abs/final.png" \
//     [--note "free-text caption under a panel" ...]
//
// Any number of --panel "Label=path" pairs (1+). Missing files render as a
// labelled placeholder rather than failing, so a partial comparison still
// builds (e.g. before the mockup exists).

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, extname } from "node:path";

function parseArgs(argv) {
  const args = { title: "Visual comparison", out: "compare.html", panels: [], notes: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--title") args.title = argv[++i];
    else if (a === "--out") args.out = argv[++i];
    else if (a === "--panel") {
      const raw = argv[++i] || "";
      const eq = raw.indexOf("=");
      args.panels.push({ label: raw.slice(0, eq).trim(), path: raw.slice(eq + 1).trim() });
    } else if (a === "--note") args.notes.push(argv[++i]);
  }
  return args;
}

const MIME = { ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg", ".webp": "image/webp", ".gif": "image/gif" };

function dataUri(path) {
  if (!path || !existsSync(path)) return null;
  const mime = MIME[extname(path).toLowerCase()] || "image/png";
  return `data:${mime};base64,${readFileSync(path).toString("base64")}`;
}

function esc(s) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const args = parseArgs(process.argv.slice(2));
if (!args.panels.length) {
  console.error("Need at least one --panel \"Label=path\".");
  process.exit(1);
}

const panelsHtml = args.panels.map((p, i) => {
  const uri = dataUri(p.path);
  const body = uri
    ? `<img src="${uri}" alt="${esc(p.label)}">`
    : `<div class="missing">no image yet<br><small>${esc(p.path || "(unset)")}</small></div>`;
  const note = args.notes[i] ? `<p class="note">${esc(args.notes[i])}</p>` : "";
  return `<figure class="panel"><figcaption>${esc(p.label)}</figcaption>${body}${note}</figure>`;
}).join("\n");

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(args.title)}</title>
<style>
  :root { color-scheme: light dark; }
  body { margin: 0; font: 15px/1.5 system-ui, sans-serif; background: #141414; color: #f4f5f1; }
  header { padding: 16px 20px; border-bottom: 3px solid #ff2e00; }
  header h1 { margin: 0; font-size: 18px; }
  header p { margin: 4px 0 0; color: #b9b9b2; font-size: 13px; }
  .grid { display: grid; grid-template-columns: repeat(${args.panels.length}, 1fr); gap: 14px; padding: 16px 20px; }
  @media (max-width: 900px) { .grid { grid-template-columns: 1fr; } }
  .panel { margin: 0; background: #1d1d1d; border: 1px solid #333; }
  .panel figcaption { padding: 8px 10px; font-weight: 700; font-size: 12px; letter-spacing: .06em; text-transform: uppercase; color: #ff7a5c; border-bottom: 1px solid #333; }
  .panel img { display: block; width: 100%; height: auto; }
  .missing { display: grid; place-items: center; min-height: 220px; color: #777; text-align: center; }
  .note { margin: 0; padding: 8px 10px; font-size: 12px; color: #b9b9b2; border-top: 1px solid #333; }
  footer { padding: 10px 20px 24px; color: #777; font-size: 12px; }
</style></head>
<body>
<header><h1>${esc(args.title)}</h1><p>Before / Proposed / Final visual verification — CLA-29 workflow</p></header>
<div class="grid">
${panelsHtml}
</div>
<footer>Generated by scripts/visual-compare.mjs. Images are embedded (portable). Open in a browser or publish as-is.</footer>
</body></html>`;

mkdirSync(dirname(args.out), { recursive: true });
writeFileSync(args.out, html);
console.log(`Wrote ${args.out} (${args.panels.length} panels).`);
